# Site settings
title: Struggle Blog
SEOTitle: 贾淙淞的博客 | Struggle Blog
header-img: img/home-bg.jpg
email: 1290891009@qq.com
description: "折腾青年|贾淙淞，Web & Mobile Lover | 这里是 @賈淙淞 的个人博客，与你一起发现更大的世界。"
keyword: "贾淙淞, 賈淙淞, Struggle,陇桥新青年, Newyouth, @賈淙淞, 贾淙淞的博客,Struggle Blog, 博客, 个人网站, 互联网, 前端, 设计, 运营, 微信, php, 贾淙淞的朋友，个人网站, 微信公众平台开发"
url: "https://struggleboy.github.io"            # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     賈淙淞
zhihu_username:     jia-cong-song
github_username:    StruggleBoy
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: struggleboy
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，我想去看看。"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
      {
        title: "哼吃潮品—— 全宇宙最好吃的肉夹馍",
        href: "http://i.senguo.cc/ffl0if6b8"
    },{
        title: "微信公众平台",
        href: "http://mp.weixin.qq.com"
    },{
        title: "微信公众平台接口测试帐号",
        href: "http://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login"
    },{
        title: "QQ互联平台",
        href: "http://connect.qq.com/"
    },{
        title: "QQ公众平台",
        href: "http://mp.qq.com"
    },{
        title: "陇桥新青年--你的大学，有我就够了！",
        href: "http://jiacongsong.com.cn/newyouth.html"
    },
]
